[workspace]
members = [
    "diesel",
    "diesel_cli",
    "diesel_codegen",
    # FIXME: getting "multiple matching crates for `diesel`" because of the shared build directory
    # "diesel_compile_tests",
    "diesel_tests",
    "diesel_infer_schema",
    "examples/mysql/getting_started_step_1",
    "examples/mysql/getting_started_step_2",
    "examples/mysql/getting_started_step_3",
    "examples/postgres/all_about_updates",
    "examples/postgres/getting_started_step_1",
    "examples/postgres/getting_started_step_2",
    "examples/postgres/getting_started_step_3",
    "examples/sqlite/getting_started_step_1",
    "examples/sqlite/getting_started_step_2",
    "examples/sqlite/getting_started_step_3",
    "examples/manual_schema_and_mappings"
]

[replace]
"diesel:0.15.2" = { path = "diesel" }
"diesel_codegen:0.15.0" = { path = "diesel_codegen" }
"diesel_infer_schema:0.15.0" = { path = "diesel_infer_schema" }
